### PlaceOrder
POST http://localhost:5251/api/v1/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI1YmM2MTUyOC03MmRmLTRhMzgtODhmYi00M2M3ZjBjMmE2NzQiLCJyb2xlIjoiVXNlciIsImVtYWlsIjoiam9obkBtYWlsLmNvbSIsIm5iZiI6MTY5MzM0NDkxMCwiZXhwIjoxNjkzMzQ2MTEwLCJpYXQiOjE2OTMzNDQ5MTAsImlzcyI6ImVjb21tZXJjZS1iYWNrZW5kIn0.gPmdUOBe_IEi-j1f28RfNu-ZAPndDY4ryWeEJIysawQ

{
  "orderProducts": [
    {
      "productId": "bc1a7415-30cb-4cf0-b28e-273b61f49513",
      "amount": 3
    }
  ]
}

# {
#   "orderProducts": [
#     {
#       "product": {
#         "title": "brioche bread",
#         "description": "brioche bread",
#         "price": 3.4,
#         "category": 0,
#         "image": null,
#         "createdAt": "0001-01-01T00:00:00+00:00",
#         "updatedAt": "0001-01-01T00:00:00+00:00"
#         },
#       "orderId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
#       "amount": 0
#     }
#   ]
# }
