### PlaceOrder
POST http://localhost:5251/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTk0YjM5Ni1lZTkyLTRkMmMtODczNi1kYjllYzYxZjhhYzQiLCJyb2xlIjoiVXNlciIsImVtYWlsIjoibWFyeUBtYWlsLmNvbSIsIm5iZiI6MTY5MzM5MTM2NSwiZXhwIjoxNjkzMzkyNTY1LCJpYXQiOjE2OTMzOTEzNjUsImlzcyI6ImVjb21tZXJjZS1iYWNrZW5kIn0.t67DkU4ZEGCY7XdmZ3mnJXp-VzWm-hQxlTyzGR2jueo

{
  "orderProducts": [
    {
      "productId": "fa420142-6bb5-4a56-8f03-00a82e551136",
      "amount": 5
    }
  ]
}

### GetAllByUserId
GET http://localhost:5251/api/v1/orders/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTk0YjM5Ni1lZTkyLTRkMmMtODczNi1kYjllYzYxZjhhYzQiLCJyb2xlIjoiVXNlciIsImVtYWlsIjoibWFyeUBtYWlsLmNvbSIsIm5iZiI6MTY5MzM5ODI3OSwiZXhwIjoxNjkzMzk5NDc5LCJpYXQiOjE2OTMzOTgyNzksImlzcyI6ImVjb21tZXJjZS1iYWNrZW5kIn0.cyeMAa9cevegQVNhHA8AZGldqVmM9lECg0EU79GcHqg

### GetOneById
GET http://localhost:5251/api/v1/orders/405309b6-bac9-43e4-9a2f-bfc30e44d4ea
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTk0YjM5Ni1lZTkyLTRkMmMtODczNi1kYjllYzYxZjhhYzQiLCJyb2xlIjoiVXNlciIsImVtYWlsIjoibWFyeUBtYWlsLmNvbSIsIm5iZiI6MTY5MzM5ODI3OSwiZXhwIjoxNjkzMzk5NDc5LCJpYXQiOjE2OTMzOTgyNzksImlzcyI6ImVjb21tZXJjZS1iYWNrZW5kIn0.cyeMAa9cevegQVNhHA8AZGldqVmM9lECg0EU79GcHqg