### PlaceOrder
POST http://localhost:5251/api/v1/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyZjg5MDk2YS01ODZlLTRhN2QtOTNhMy1mM2VjMGEzZmY3MTEiLCJyb2xlIjoiVXNlciIsImVtYWlsIjoibWFyeUBtYWlsLmNvbSIsIm5iZiI6MTY5MjMwOTcxMCwiZXhwIjoxNjkyMzEwOTEwLCJpYXQiOjE2OTIzMDk3MTAsImlzcyI6ImVjb21tZXJjZS1iYWNrZW5kIn0.RpPshhQ_CTdf6-nJP8xBk1vl8SlYBUAbkDU4pMRx2mM

{
  "orderProducts": [
    {
      "productId": "fcca6f44-25b7-46ab-b62c-0c98b7694b92",
      "amount": 3
    }
  ]
}

# {
#   "orderProducts": [
#     {
#       "product": {
#         "title": "brioche bread",
#         "description": "brioche bread",
#         "price": 3.4,
#         "category": 0,
#         "image": null,
#         "createdAt": "0001-01-01T00:00:00+00:00",
#         "updatedAt": "0001-01-01T00:00:00+00:00"
#         },
#       "orderId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
#       "amount": 0
#     }
#   ]
# }
