//CreateOne
###
POST http://localhost:5251/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhYmNkNzAzZi0zZTU0LTQ5YjItOGNmYy04ODQ3OGJlZTgxNGUiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6ImtpbUBtYWlsLmNvbSIsIm5iZiI6MTY5MzM4ODQzNiwiZXhwIjoxNjkzMzg5NjM2LCJpYXQiOjE2OTMzODg0MzYsImlzcyI6ImVjb21tZXJjZS1iYWNrZW5kIn0.bB4M-b5K6rd5CbsV_GiBN8VFOttf7-qb7L3Zl8uZPWw

{
  "title": "JBL Tour One M2",
  "description": "JBL headphones",
  "price": 349.99,
  "category": 4,
  "inventory": 50,
  "image": {
    "link": "https://www.gigantti.fi/image/dv_web_D180001002743559/304656/jbl-tour-one-langattomat-around-ear-kuulokkeet-musta--pdp_zoom-3000.jpg"
  }
}

###
POST http://localhost:5251/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhYmNkNzAzZi0zZTU0LTQ5YjItOGNmYy04ODQ3OGJlZTgxNGUiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6ImtpbUBtYWlsLmNvbSIsIm5iZiI6MTY5MzM4ODQzNiwiZXhwIjoxNjkzMzg5NjM2LCJpYXQiOjE2OTMzODg0MzYsImlzcyI6ImVjb21tZXJjZS1iYWNrZW5kIn0.bB4M-b5K6rd5CbsV_GiBN8VFOttf7-qb7L3Zl8uZPWw

{
  "title": "Sweatshirt",
  "description": "sweatshirt in beige",
  "price": 34.55,
  "category": 1,
  "inventory": 15,
  "image": {
    "link": "string"
  }
}

//GetAll
###
GET http://localhost:5251/api/v1/Products

//GetOneById
###
GET http://localhost:5251/api/v1/Products/3a06ff0b-c9eb-4567-b15d-023267e03d1d

//UpdateOneById
###
PATCH http://localhost:5251/api/v1/Products/0ac27890-e425-42c5-97d7-5a2f9424a789
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJiOGIxZTI1YS1mMDY5LTRiNjAtOTVkZi04MjJkOTExMDRhNDgiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6ImtpbUBtYWlsLmNvbSIsIm5iZiI6MTY5MjIyMDQ3MCwiZXhwIjoxNjkyMjIxNjcwLCJpYXQiOjE2OTIyMjA0NzAsImlzcyI6ImVjb21tZXJjZS1iYWNrZW5kIn0.3-2vJEZpzzz9Bk0q0YpEJiMtClN_5YAJ9xn_gEsVbso

{
  "title": "black t-shirt",
  "description": "string",
  "price": 0,
  "category": 0,
  "inventory": 0
}

//DeleteOneById
###
DELETE http://localhost:5251/api/v1/Products/5abd52b9-04bf-40c5-8e30-4225dcd54748
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJiOGIxZTI1YS1mMDY5LTRiNjAtOTVkZi04MjJkOTExMDRhNDgiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6ImtpbUBtYWlsLmNvbSIsIm5iZiI6MTY5MjIyMDQ3MCwiZXhwIjoxNjkyMjIxNjcwLCJpYXQiOjE2OTIyMjA0NzAsImlzcyI6ImVjb21tZXJjZS1iYWNrZW5kIn0.3-2vJEZpzzz9Bk0q0YpEJiMtClN_5YAJ9xn_gEsVbso








